// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKEe9aZQgZMuhnSUhWDMpkZZsW0UDtMxI',
    appId: '1:686929535289:web:306910c1f288f63c3348e8',
    messagingSenderId: '686929535289',
    projectId: 'fooddelivery-1df7f',
    authDomain: 'fooddelivery-1df7f.firebaseapp.com',
    storageBucket: 'fooddelivery-1df7f.appspot.com',
    measurementId: 'G-0ZQ6SFVM6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOMXAd-lEIifVxyf6CTL6z_MBCywazXCs',
    appId: '1:686929535289:android:c6bafa8ae34829163348e8',
    messagingSenderId: '686929535289',
    projectId: 'fooddelivery-1df7f',
    storageBucket: 'fooddelivery-1df7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8VtFfL4e6yTHYG0xdy3yNZtyxgsRCUh0',
    appId: '1:686929535289:ios:a8e073c01705fe773348e8',
    messagingSenderId: '686929535289',
    projectId: 'fooddelivery-1df7f',
    storageBucket: 'fooddelivery-1df7f.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8VtFfL4e6yTHYG0xdy3yNZtyxgsRCUh0',
    appId: '1:686929535289:ios:a8e073c01705fe773348e8',
    messagingSenderId: '686929535289',
    projectId: 'fooddelivery-1df7f',
    storageBucket: 'fooddelivery-1df7f.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKEe9aZQgZMuhnSUhWDMpkZZsW0UDtMxI',
    appId: '1:686929535289:web:8678b2df3de05c9a3348e8',
    messagingSenderId: '686929535289',
    projectId: 'fooddelivery-1df7f',
    authDomain: 'fooddelivery-1df7f.firebaseapp.com',
    storageBucket: 'fooddelivery-1df7f.appspot.com',
    measurementId: 'G-ZYSQENM0Q8',
  );
}
